version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: compose-mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: [
      "--log-bin=mysql-bin",
      "--server-id=1"
    ]
    networks:
      - compose-net

  rabbit:
    image: rabbitmq:3-management
    container_name: compose-rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - compose-net

  spring-boot:
    image: compose-spring-boot:v1
    container_name: compose-spring-boot
    build:
      context: .
      dockerfile: dockerfile-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbit
    networks:
      - compose-net

networks:
  compose-net:
