FROM openjdk:11
RUN mkdir -p /app/build/libs
WORKDIR /app
COPY ../spring-boot-myproject-service/target/myproject-spring-boot.jar /app/build/libs
EXPOSE 8080
CMD ["java", "-jar", "build/libs/myproject-spring-boot.jar","--spring.profiles.active=docker"]