FROM openjdk:11
RUN mkdir -p /app/build/libs
WORKDIR /app
COPY spring-boot-myproject.jar /app/build/libs
EXPOSE 8080
CMD ["java", "-jar", "build/libs/spring-boot-myproject.jar","--spring.profiles.active=docker"]
