server:
  port: 8080

spring:
  application:
    name: my-project
  profiles:
    active: dev
#  main:
#    lazy-initialization: true

hello-world:
  enabled: true
  name: 'Foo'
  age: 20
  sex: 'm'

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

# mybatis
mybatis:
  mapper-locations: classpath:cn/com/springboot/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    cn.com.springboot: debug
