spring:
  application:
    name: springboot-practice

server:
  servlet:
    encoding:
      force: true
  shutdown: graceful

management:
  endpoints:
    enabled-by-default: false


# 自动配置
hello-world:
  enabled: true
  name: 'Foo'
  age: 20
  sex: 'm'

# 日志
logging:
  level:
    root: info
    cn.com.springboot: debug
  pattern:
    console: "%d %clr(%-5p) %clr(${PID:-}){magenta} --- [%t] %clr(%c{10}.%M){cyan} \\(%file:%line\\) %m%n"