spring:
  application:
    name: spring-boot-practice
  devtools:
    restart:
      poll-interval: 500ms
      quiet-period: 100ms
  datasource:
    url: jdbc:h2:mem:spring_boot;DATABASE_TO_UPPER=false;MODE=MYSQL;
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    username: root
    password: password
  h2:
    console:
      enabled: true
  redis:
    redisson:
      config: classpath:redisson.yaml
#  kafka:
#    consumer:
#      bootstrap-servers: 192.168.56.10:9092
#      group-id: 1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: 192.168.56.10:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  servlet:
    encoding:
      force: true
  shutdown: graceful

management:
  endpoints:
    enabled-by-default: false

# 分页助手
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


# 自动配置
hello-world:
  enabled: true
  name: 'Foo'
  age: 20
  sex: 'm'

# 日志
logging:
  level:
    root: info
    cn.com.springboot: debug
  pattern:
    console: "%d %clr(%-5p) %clr(${PID:-}){magenta} --- [%t] %clr(%c{10}.%M){cyan} \\(%file:%line\\) %m%n"