spring:
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  # mq
  rabbitmq:
    host: localhost
    port: 5672