#spring:
#  redis:
#    host: 127.0.0.1
#    database: 0
#    port: 6379
#    timeout: 5000ms
#    lettuce:
#      pool:
#        max-active: 50
#        min-idle: 5
#    redisson:
#      config: classpath:redisson.yaml